name: CI

on:
  push:
    branches:
      - pipeline*

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - name: Test
        run: npm run test:ci

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: npm run lint

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - name: Build
        run: npm run build:ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/workshop-devops-fe-angular


# Steps
# 1. Make sure dependencies are installed
#   - Optionally cache dependencies
# 2. Test and lint the application
#    - This can be run in parallel
# 3. If the testing and linting succeeds create production distribution
# 4. Upload the artifacts

# Create a separate workflow to deploy the app or add CD step here

# Useful actions
# actions/setup-node@v3
# actions/checkout@v3
# actions/setup-node@v3
# actions/upload-artifact@v3
